2017-05-14 17:28:29.691 [error] <0.142.0> CRASH REPORT Process <0.142.0> with 0 neighbours exited with reason: no function clause matching lists:foreach(#Fun<group_sup.4.17263849>, {atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,...}}}}) line 1337 in gen_server:init_it/6 line 352
2017-05-14 17:28:29.692 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching lists:foreach(#Fun<group_sup.4.17263849>, {atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,...}}}}) line 1337 in context start_error
2017-05-14 17:28:29.692 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{lists,foreach,[#Fun<group_sup.4.17263849>,{atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,allowed}}}}],[{file,"lists.erl"},{line,1337}]},{group_sup,init,1,[{file,"src/logic/group_sup.erl"},{line,72}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in context start_error
2017-05-14 17:28:29.692 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,group_sup,{function_clause,[{lists,foreach,[#Fun<group_sup.4.17263849>,{atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,allowed}}}}],[{file,"lists.erl"},{line,1337}]},{group_sup,init,1,[{file,"src/logic/group_sup.erl"},{line,72}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}},...} in application_master:init/4 line 134
2017-05-14 17:41:42.260 [error] <0.142.0> CRASH REPORT Process <0.142.0> with 0 neighbours exited with reason: no function clause matching lists:foreach(#Fun<group_sup.4.17263849>, {atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,...}}}}) line 1337 in gen_server:init_it/6 line 352
2017-05-14 17:41:42.260 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching lists:foreach(#Fun<group_sup.4.17263849>, {atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,...}}}}) line 1337 in context start_error
2017-05-14 17:41:42.261 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{lists,foreach,[#Fun<group_sup.4.17263849>,{atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,allowed}}}}],[{file,"lists.erl"},{line,1337}]},{group_sup,init,1,[{file,"src/logic/group_sup.erl"},{line,72}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in context start_error
2017-05-14 17:43:01.240 [error] <0.143.0> CRASH REPORT Process <0.143.0> with 0 neighbours exited with reason: no function clause matching lists:foreach(#Fun<group_sup.4.17263849>, {atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,...}}}}) line 1337 in gen_server:init_it/6 line 352
2017-05-14 17:43:01.240 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching lists:foreach(#Fun<group_sup.4.17263849>, {atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,...}}}}) line 1337 in context start_error
2017-05-14 17:43:01.241 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{lists,foreach,[#Fun<group_sup.4.17263849>,{atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,allowed}}}}],[{file,"lists.erl"},{line,1337}]},{group_sup,init,1,[{file,"src/logic/group_sup.erl"},{line,72}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in context start_error
2017-05-14 17:46:28.369 [error] <0.142.0> CRASH REPORT Process <0.142.0> with 0 neighbours exited with reason: no function clause matching lists:foreach(#Fun<group_sup.6.114317290>, {atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,...}}}}) line 1337 in gen_server:init_it/6 line 352
2017-05-14 17:46:28.369 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching lists:foreach(#Fun<group_sup.6.114317290>, {atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,...}}}}) line 1337 in context start_error
2017-05-14 17:46:28.369 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{lists,foreach,[#Fun<group_sup.6.114317290>,{atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,allowed}}}}],[{file,"lists.erl"},{line,1337}]},{group_sup,init,1,[{file,"src/logic/group_sup.erl"},{line,73}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in context start_error
2017-05-14 17:46:28.370 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,group_sup,{function_clause,[{lists,foreach,[#Fun<group_sup.6.114317290>,{atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,allowed}}}}],[{file,"lists.erl"},{line,1337}]},{group_sup,init,1,[{file,"src/logic/group_sup.erl"},{line,73}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}},...} in application_master:init/4 line 134
2017-05-14 17:46:49.294 [error] <0.142.0> CRASH REPORT Process <0.142.0> with 0 neighbours exited with reason: no function clause matching lists:foreach(#Fun<group_sup.6.39345746>, {atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,...}}}}) line 1337 in gen_server:init_it/6 line 352
2017-05-14 17:46:49.294 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching lists:foreach(#Fun<group_sup.6.39345746>, {atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,...}}}}) line 1337 in context start_error
2017-05-14 17:46:49.294 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{lists,foreach,[#Fun<group_sup.6.39345746>,{atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,allowed}}}}],[{file,"lists.erl"},{line,1337}]},{group_sup,init,1,[{file,"src/logic/group_sup.erl"},{line,73}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in context start_error
2017-05-14 17:46:49.295 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,group_sup,{function_clause,[{lists,foreach,[#Fun<group_sup.6.39345746>,{atomic,{qlc_handle,{qlc_lc,#Fun<mod_group_sup.1.124098997>,{qlc_opt,false,false,-1,any,[],any,524288,allowed}}}}],[{file,"lists.erl"},{line,1337}]},{group_sup,init,1,[{file,"src/logic/group_sup.erl"},{line,73}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}},...} in application_master:init/4 line 134
2017-05-14 18:48:31.267 [error] <0.145.0> CRASH REPORT Process <0.145.0> with 0 neighbours exited with reason: no function clause matching supervisor:check_startspec(ok, []) line 1295 in gen_server:init_it/6 line 352
2017-05-14 18:48:31.267 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching supervisor:check_startspec(ok, []) line 1295 in context start_error
2017-05-14 18:48:31.267 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{supervisor,check_startspec,[ok,[]],[{file,"supervisor.erl"},{line,1295}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,312}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in context start_error
2017-05-14 18:51:18.988 [error] <0.145.0> CRASH REPORT Process <0.145.0> with 0 neighbours exited with reason: no function clause matching supervisor:check_startspec(ok, []) line 1295 in gen_server:init_it/6 line 352
2017-05-14 18:51:18.988 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching supervisor:check_startspec(ok, []) line 1295 in context start_error
2017-05-14 18:51:18.989 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{supervisor,check_startspec,[ok,[]],[{file,"supervisor.erl"},{line,1295}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,312}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in context start_error
2017-05-14 18:52:15.924 [error] <0.99.0> Supervisor control_sup had child user_sup started with user_sup:start_link() at undefined exit with reason {'EXIT',{undef,[{user_sup,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2017-05-14 18:54:19.589 [error] <0.145.0> Supervisor group_sup had child 1 started with group:start_link(1) at undefined exit with reason {'EXIT',{undef,[{group,start_link,[1],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2017-05-14 18:54:19.590 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,1,{'EXIT',{undef,[{group,start_link,[1],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2017-05-14 19:00:11.805 [error] <0.147.0> Supervisor group_sup had child 2 started with group:start_link(2) at undefined exit with reason {already_started,<0.149.0>} in context start_error
2017-05-14 19:00:11.805 [error] <0.101.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,2,{already_started,<0.149.0>}}} in context start_error
2017-05-14 19:00:11.805 [error] <0.100.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{shutdown,{failed_to_start_child,2,{already_started,<0.149.0>}}}}} in context start_error
2017-05-14 19:00:11.806 [error] <0.98.0> CRASH REPORT Process <0.98.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,group_sup,{shutdown,{failed_to_start_child,2,{already_started,<0.149.0>}}}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-14 19:01:03.904 [error] <0.99.0> Supervisor control_sup had child user_sup started with user_sup:start_link() at undefined exit with reason {'EXIT',{undef,[{user_sup,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2017-05-14 19:01:03.905 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,user_sup,{'EXIT',{undef,[{user_sup,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2017-05-14 19:01:03.905 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,user_sup,{'EXIT',{undef,[{user_sup,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-14 19:13:40.082 [error] <0.150.0> Supervisor client_sup had child 'AName' started with 'AModule':start_link() at undefined exit with reason {'EXIT',{undef,[{'AModule',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2017-05-14 19:13:40.083 [error] <0.99.0> Supervisor control_sup had child client_sup started with client_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,'AName',{'EXIT',{undef,[{'AModule',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2017-05-14 19:18:50.112 [error] <0.150.0> CRASH REPORT Process <0.150.0> with 0 neighbours exited with reason: {start_spec,{invalid_mfa,{client,[]}}} in gen_server:init_it/6 line 344
2017-05-14 19:18:50.112 [error] <0.99.0> Supervisor control_sup had child client_sup started with client_sup:start_link() at undefined exit with reason {start_spec,{invalid_mfa,{client,[]}}} in context start_error
2017-05-14 19:18:50.112 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,client_sup,{start_spec,{invalid_mfa,{client,[]}}}}} in context start_error
2017-05-15 10:48:05.802 [error] <0.149.0> gen_server <0.149.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:05.802 [error] <0.150.0> gen_server <0.150.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:05.802 [error] <0.151.0> gen_server <0.151.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:06.135 [error] <0.149.0> CRASH REPORT Process <0.149.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.135 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.135 [error] <0.150.0> CRASH REPORT Process <0.150.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.135 [error] <0.147.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.149.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.135 [error] <0.153.0> gen_server <0.153.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:06.135 [error] <0.153.0> CRASH REPORT Process <0.153.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.135 [error] <0.147.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.151.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.135 [error] <0.154.0> gen_server <0.154.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:06.135 [error] <0.154.0> CRASH REPORT Process <0.154.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.135 [error] <0.147.0> Supervisor group_sup had child 2 started with group:start_link(2) at <0.150.0> exit with reason no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.136 [error] <0.155.0> gen_server <0.155.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:06.136 [error] <0.155.0> CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.136 [error] <0.147.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.153.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.136 [error] <0.156.0> gen_server <0.156.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:06.136 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.136 [error] <0.147.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.154.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.136 [error] <0.157.0> gen_server <0.157.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:06.136 [error] <0.157.0> CRASH REPORT Process <0.157.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.136 [error] <0.147.0> Supervisor group_sup had child 2 started with group:start_link(2) at <0.155.0> exit with reason no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.136 [error] <0.158.0> gen_server <0.158.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:06.136 [error] <0.158.0> CRASH REPORT Process <0.158.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.136 [error] <0.147.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.156.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.136 [error] <0.159.0> gen_server <0.159.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:06.136 [error] <0.159.0> CRASH REPORT Process <0.159.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.136 [error] <0.147.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.157.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.137 [error] <0.160.0> gen_server <0.160.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:06.137 [error] <0.160.0> CRASH REPORT Process <0.160.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.137 [error] <0.147.0> Supervisor group_sup had child 2 started with group:start_link(2) at <0.158.0> exit with reason no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.137 [error] <0.161.0> gen_server <0.161.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:06.137 [error] <0.161.0> CRASH REPORT Process <0.161.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.137 [error] <0.147.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.159.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.137 [error] <0.162.0> gen_server <0.162.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:06.137 [error] <0.162.0> CRASH REPORT Process <0.162.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.137 [error] <0.147.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.160.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.137 [error] <0.163.0> gen_server <0.163.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:06.137 [error] <0.163.0> CRASH REPORT Process <0.163.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.137 [error] <0.147.0> Supervisor group_sup had child 2 started with group:start_link(2) at <0.161.0> exit with reason no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.137 [error] <0.164.0> gen_server <0.164.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:06.137 [error] <0.164.0> CRASH REPORT Process <0.164.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.137 [error] <0.147.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.162.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.137 [error] <0.165.0> gen_server <0.165.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:06.138 [error] <0.165.0> CRASH REPORT Process <0.165.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.138 [error] <0.147.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.163.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.138 [error] <0.166.0> gen_server <0.166.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:06.138 [error] <0.166.0> CRASH REPORT Process <0.166.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.138 [error] <0.147.0> Supervisor group_sup had child 2 started with group:start_link(2) at <0.164.0> exit with reason no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.138 [error] <0.167.0> gen_server <0.167.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:06.138 [error] <0.167.0> CRASH REPORT Process <0.167.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.138 [error] <0.147.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.165.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:06.138 [error] <0.168.0> gen_server <0.168.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:06.138 [error] <0.168.0> CRASH REPORT Process <0.168.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:06.138 [error] <0.147.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.166.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:19.859 [error] <0.6180.0> gen_server <0.6180.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:19.859 [error] <0.6180.0> CRASH REPORT Process <0.6180.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.859 [error] <0.6181.0> gen_server <0.6181.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:19.860 [error] <0.6181.0> CRASH REPORT Process <0.6181.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.860 [error] <0.6182.0> gen_server <0.6182.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:19.860 [error] <0.6182.0> CRASH REPORT Process <0.6182.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.860 [error] <0.6178.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.6180.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:19.860 [error] <0.6183.0> gen_server <0.6183.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:19.860 [error] <0.6183.0> CRASH REPORT Process <0.6183.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.860 [error] <0.6178.0> Supervisor group_sup had child 2 started with group:start_link(2) at <0.6181.0> exit with reason no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in context child_terminated
2017-05-15 10:48:19.860 [error] <0.6184.0> gen_server <0.6184.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:19.860 [error] <0.6184.0> CRASH REPORT Process <0.6184.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.860 [error] <0.6178.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.6182.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:19.861 [error] <0.6185.0> gen_server <0.6185.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:19.861 [error] <0.6185.0> CRASH REPORT Process <0.6185.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.861 [error] <0.6178.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.6183.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:19.861 [error] <0.6186.0> gen_server <0.6186.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:19.861 [error] <0.6186.0> CRASH REPORT Process <0.6186.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.861 [error] <0.6178.0> Supervisor group_sup had child 2 started with group:start_link(2) at <0.6184.0> exit with reason no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in context child_terminated
2017-05-15 10:48:19.861 [error] <0.6187.0> gen_server <0.6187.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:19.861 [error] <0.6187.0> CRASH REPORT Process <0.6187.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.861 [error] <0.6178.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.6185.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:19.861 [error] <0.6188.0> gen_server <0.6188.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:19.862 [error] <0.6188.0> CRASH REPORT Process <0.6188.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.862 [error] <0.6178.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.6186.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:19.862 [error] <0.6189.0> gen_server <0.6189.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:19.862 [error] <0.6189.0> CRASH REPORT Process <0.6189.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.862 [error] <0.6178.0> Supervisor group_sup had child 2 started with group:start_link(2) at <0.6187.0> exit with reason no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in context child_terminated
2017-05-15 10:48:19.862 [error] <0.6190.0> gen_server <0.6190.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:19.862 [error] <0.6190.0> CRASH REPORT Process <0.6190.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.862 [error] <0.6178.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.6188.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:19.862 [error] <0.6191.0> gen_server <0.6191.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:19.862 [error] <0.6191.0> CRASH REPORT Process <0.6191.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:19.862 [error] <0.6178.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.6189.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:19.862 [error] <0.6192.0> gen_server <0.6192.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:19.862 [error] <0.6192.0> CRASH REPORT Process <0.6192.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:20.000 [error] <0.9262.0> gen_server <0.9262.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:20.000 [error] <0.9262.0> CRASH REPORT Process <0.9262.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:20.000 [error] <0.9193.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.9260.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:20.000 [error] <0.9263.0> gen_server <0.9263.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:20.000 [error] <0.9263.0> CRASH REPORT Process <0.9263.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:20.000 [error] <0.9193.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.9261.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:20.000 [error] <0.9264.0> gen_server <0.9264.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:20.000 [error] <0.9264.0> CRASH REPORT Process <0.9264.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:20.000 [error] <0.9193.0> Supervisor group_sup had child 2 started with group:start_link(2) at <0.9262.0> exit with reason no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in context child_terminated
2017-05-15 10:48:20.000 [error] <0.9265.0> gen_server <0.9265.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:20.001 [error] <0.9265.0> CRASH REPORT Process <0.9265.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:20.001 [error] <0.9193.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.9263.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:20.001 [error] <0.9266.0> gen_server <0.9266.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:20.001 [error] <0.9266.0> CRASH REPORT Process <0.9266.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:20.001 [error] <0.9193.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.9264.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:20.001 [error] <0.9267.0> gen_server <0.9267.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:20.001 [error] <0.9267.0> CRASH REPORT Process <0.9267.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:20.001 [error] <0.9193.0> Supervisor group_sup had child 2 started with group:start_link(2) at <0.9265.0> exit with reason no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in context child_terminated
2017-05-15 10:48:20.001 [error] <0.9268.0> gen_server <0.9268.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101
2017-05-15 10:48:20.001 [error] <0.9268.0> CRASH REPORT Process <0.9268.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:20.001 [error] <0.9193.0> Supervisor group_sup had child 3 started with group:start_link(3) at <0.9266.0> exit with reason no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in context child_terminated
2017-05-15 10:48:20.001 [error] <0.9269.0> gen_server <0.9269.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101
2017-05-15 10:48:20.001 [error] <0.9269.0> CRASH REPORT Process <0.9269.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,3,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:20.002 [error] <0.9193.0> Supervisor group_sup had child 1 started with group:start_link(1) at <0.9267.0> exit with reason no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in context child_terminated
2017-05-15 10:48:20.002 [error] <0.9270.0> gen_server <0.9270.0> terminated with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101
2017-05-15 10:48:20.002 [error] <0.9270.0> CRASH REPORT Process <0.9270.0> with 0 neighbours exited with reason: no function clause matching group:handle_cast({online}, {state,1,undefined}) line 101 in gen_server:terminate/7 line 812
2017-05-15 10:48:20.002 [error] <0.9193.0> Supervisor group_sup had child 2 started with group:start_link(2) at <0.9268.0> exit with reason no function clause matching group:handle_cast({online}, {state,2,undefined}) line 101 in context child_terminated
2017-05-17 20:51:17.119 [error] <0.120.0> CRASH REPORT Process <0.120.0> with 0 neighbours exited with reason: no function clause matching mod_mnesia:'-get_group_keys/0-lc$^0/1-0-'({qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.6445833..>,...}}) line 17 in gen_server:init_it/6 line 352
2017-05-17 20:51:17.119 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching mod_mnesia:'-get_group_keys/0-lc$^0/1-0-'({qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.6445833..>,...}}) line 17 in context start_error
2017-05-17 20:51:17.119 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{mod_mnesia,'-get_group_keys/0-lc$^0/1-0-',[{qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.64458334>,#Fun<mnesia.25.64458334>,#Fun<mnesia.28.64458334>,#Fun<mnesia.27.64458334>,#Fun<mnesia.26.64458334>,'=:=',undefined,no_match_spec}}],[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{mod_mnesia,get_group_keys,0,[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{group_sup,init,1,[{file,"src/logic..."},...]},...]}}} in context start_error
2017-05-17 20:51:17.119 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,group_sup,{function_clause,[{mod_mnesia,'-get_group_keys/0-lc$^0/1-0-',[{qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.64458334>,#Fun<mnesia.25.64458334>,#Fun<mnesia.28.64458334>,#Fun<mnesia.27.64458334>,#Fun<mnesia.26.64458334>,'=:=',undefined,no_match_spec}}],[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{mod_mnesia,get_group_keys,0,[{file,"src/mod/mod_mnesia.erl"},{...}]},...]}}}}},...} in application_master:init/4 line 134
2017-05-17 20:52:22.777 [error] <0.120.0> CRASH REPORT Process <0.120.0> with 0 neighbours exited with reason: no function clause matching mod_mnesia:'-get_group_keys/0-lc$^0/1-0-'({qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.6445833..>,...}}) line 17 in gen_server:init_it/6 line 352
2017-05-17 20:52:22.777 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching mod_mnesia:'-get_group_keys/0-lc$^0/1-0-'({qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.6445833..>,...}}) line 17 in context start_error
2017-05-17 20:52:22.777 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{mod_mnesia,'-get_group_keys/0-lc$^0/1-0-',[{qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.64458334>,#Fun<mnesia.25.64458334>,#Fun<mnesia.28.64458334>,#Fun<mnesia.27.64458334>,#Fun<mnesia.26.64458334>,'=:=',undefined,no_match_spec}}],[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{mod_mnesia,get_group_keys,0,[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{group_sup,init,1,[{file,"src/logic..."},...]},...]}}} in context start_error
2017-05-17 21:03:30.108 [error] <0.120.0> CRASH REPORT Process <0.120.0> with 0 neighbours exited with reason: no function clause matching mod_mnesia:'-get_group_keys/0-lc$^0/1-0-'({qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.6445833..>,...}}) line 17 in gen_server:init_it/6 line 352
2017-05-17 21:03:30.108 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching mod_mnesia:'-get_group_keys/0-lc$^0/1-0-'({qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.6445833..>,...}}) line 17 in context start_error
2017-05-17 21:03:30.108 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{mod_mnesia,'-get_group_keys/0-lc$^0/1-0-',[{qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.64458334>,#Fun<mnesia.25.64458334>,#Fun<mnesia.28.64458334>,#Fun<mnesia.27.64458334>,#Fun<mnesia.26.64458334>,'=:=',undefined,no_match_spec}}],[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{mod_mnesia,get_group_keys,0,[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{group_sup,init,1,[{file,"src/logic..."},...]},...]}}} in context start_error
2017-05-17 21:03:47.508 [error] <0.119.0> CRASH REPORT Process <0.119.0> with 0 neighbours exited with reason: no function clause matching mod_mnesia:'-get_group_keys/0-lc$^0/1-0-'({qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.6445833..>,...}}) line 17 in gen_server:init_it/6 line 352
2017-05-17 21:03:47.509 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching mod_mnesia:'-get_group_keys/0-lc$^0/1-0-'({qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.6445833..>,...}}) line 17 in context start_error
2017-05-17 21:03:47.509 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{mod_mnesia,'-get_group_keys/0-lc$^0/1-0-',[{qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.64458334>,#Fun<mnesia.25.64458334>,#Fun<mnesia.28.64458334>,#Fun<mnesia.27.64458334>,#Fun<mnesia.26.64458334>,'=:=',undefined,no_match_spec}}],[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{mod_mnesia,get_group_keys,0,[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{group_sup,init,1,[{file,"src/logic..."},...]},...]}}} in context start_error
2017-05-17 21:03:47.509 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,group_sup,{function_clause,[{mod_mnesia,'-get_group_keys/0-lc$^0/1-0-',[{qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.64458334>,#Fun<mnesia.25.64458334>,#Fun<mnesia.28.64458334>,#Fun<mnesia.27.64458334>,#Fun<mnesia.26.64458334>,'=:=',undefined,no_match_spec}}],[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{mod_mnesia,get_group_keys,0,[{file,"src/mod/mod_mnesia.erl"},{...}]},...]}}}}},...} in application_master:init/4 line 134
2017-05-17 21:05:34.056 [error] <0.119.0> CRASH REPORT Process <0.119.0> with 0 neighbours exited with reason: no function clause matching mod_mnesia:'-get_group_keys/0-lc$^0/1-0-'({qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.6445833..>,...}}) line 17 in gen_server:init_it/6 line 352
2017-05-17 21:05:34.056 [error] <0.99.0> Supervisor control_sup had child group_sup started with group_sup:start_link() at undefined exit with reason no function clause matching mod_mnesia:'-get_group_keys/0-lc$^0/1-0-'({qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.6445833..>,...}}) line 17 in context start_error
2017-05-17 21:05:34.057 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,group_sup,{function_clause,[{mod_mnesia,'-get_group_keys/0-lc$^0/1-0-',[{qlc_handle,{qlc_table,#Fun<mnesia.22.64458334>,true,#Fun<mnesia.23.64458334>,#Fun<mnesia.24.64458334>,#Fun<mnesia.25.64458334>,#Fun<mnesia.28.64458334>,#Fun<mnesia.27.64458334>,#Fun<mnesia.26.64458334>,'=:=',undefined,no_match_spec}}],[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{mod_mnesia,get_group_keys,0,[{file,"src/mod/mod_mnesia.erl"},{line,17}]},{group_sup,init,1,[{file,"src/logic..."},...]},...]}}} in context start_error
2017-05-17 21:08:27.583 [error] <0.120.0> CRASH REPORT Process <0.120.0> with 0 neighbours exited with reason: {bad_start_spec,[]} in gen_server:init_it/6 line 344
2017-05-17 21:08:27.583 [error] <0.99.0> Supervisor control_sup had child client_sup started with client_sup:start_link() at undefined exit with reason {bad_start_spec,[]} in context start_error
2017-05-17 21:08:27.583 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}} in context start_error
2017-05-17 21:08:27.584 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-17 21:09:42.909 [error] <0.120.0> CRASH REPORT Process <0.120.0> with 0 neighbours exited with reason: {bad_start_spec,[]} in gen_server:init_it/6 line 344
2017-05-17 21:09:42.909 [error] <0.99.0> Supervisor control_sup had child client_sup started with client_sup:start_link() at undefined exit with reason {bad_start_spec,[]} in context start_error
2017-05-17 21:09:42.909 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}} in context start_error
2017-05-17 21:09:42.910 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-17 21:11:04.628 [error] <0.121.0> CRASH REPORT Process <0.121.0> with 0 neighbours exited with reason: {bad_start_spec,[]} in gen_server:init_it/6 line 344
2017-05-17 21:11:04.628 [error] <0.99.0> Supervisor control_sup had child client_sup started with client_sup:start_link() at undefined exit with reason {bad_start_spec,[]} in context start_error
2017-05-17 21:11:04.628 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}} in context start_error
2017-05-17 21:12:18.494 [error] <0.121.0> CRASH REPORT Process <0.121.0> with 0 neighbours exited with reason: {bad_start_spec,[]} in gen_server:init_it/6 line 344
2017-05-17 21:12:18.494 [error] <0.99.0> Supervisor control_sup had child client_sup started with client_sup:start_link() at undefined exit with reason {bad_start_spec,[]} in context start_error
2017-05-17 21:12:18.494 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}} in context start_error
2017-05-17 21:12:18.494 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-17 21:13:26.099 [error] <0.121.0> CRASH REPORT Process <0.121.0> with 0 neighbours exited with reason: {bad_start_spec,[]} in gen_server:init_it/6 line 344
2017-05-17 21:13:26.099 [error] <0.99.0> Supervisor control_sup had child client_sup started with client_sup:start_link() at undefined exit with reason {bad_start_spec,[]} in context start_error
2017-05-17 21:13:26.099 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}} in context start_error
2017-05-17 21:13:26.099 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-17 21:14:33.325 [error] <0.121.0> CRASH REPORT Process <0.121.0> with 0 neighbours exited with reason: {bad_start_spec,[]} in gen_server:init_it/6 line 344
2017-05-17 21:14:33.325 [error] <0.99.0> Supervisor control_sup had child client_sup started with client_sup:start_link() at undefined exit with reason {bad_start_spec,[]} in context start_error
2017-05-17 21:14:33.326 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}} in context start_error
2017-05-17 21:17:03.596 [error] <0.121.0> CRASH REPORT Process <0.121.0> with 0 neighbours exited with reason: {bad_start_spec,[]} in gen_server:init_it/6 line 344
2017-05-17 21:17:03.597 [error] <0.99.0> Supervisor control_sup had child client_sup started with client_sup:start_link() at undefined exit with reason {bad_start_spec,[]} in context start_error
2017-05-17 21:17:03.597 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}} in context start_error
2017-05-17 21:17:03.597 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,client_sup,{bad_start_spec,[]}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-17 21:18:54.007 [error] <0.122.0> CRASH REPORT Process <0.122.0> with 0 neighbours exited with reason: {bad_start_spec,[]} in gen_server:init_it/6 line 344
2017-05-17 21:18:54.007 [error] <0.99.0> Supervisor control_sup had child tcp_agent_sup started with tcp_agent_sup:start_link() at undefined exit with reason {bad_start_spec,[]} in context start_error
2017-05-17 21:18:54.007 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,tcp_agent_sup,{bad_start_spec,[]}}} in context start_error
2017-05-17 21:18:54.007 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,tcp_agent_sup,{bad_start_spec,[]}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-18 16:14:12.368 [error] <0.99.0> Supervisor control_sup had child tcp_acceptor started with tcp_acceptor:start() at undefined exit with reason {'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2017-05-18 16:14:12.369 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,tcp_acceptor,{'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2017-05-18 16:14:36.658 [error] <0.99.0> Supervisor control_sup had child tcp_acceptor started with tcp_acceptor:start() at undefined exit with reason {'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2017-05-18 16:14:36.658 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,tcp_acceptor,{'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2017-05-18 16:14:36.658 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,tcp_acceptor,{'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-18 16:16:17.716 [error] <0.99.0> Supervisor control_sup had child tcp_acceptor started with tcp_acceptor:start() at undefined exit with reason {'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2017-05-18 16:16:17.717 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,tcp_acceptor,{'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2017-05-18 16:17:29.516 [error] <0.99.0> Supervisor control_sup had child tcp_acceptor started with tcp_acceptor:start() at undefined exit with reason {'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2017-05-18 16:17:29.517 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,tcp_acceptor,{'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2017-05-18 16:17:29.517 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,tcp_acceptor,{'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-18 16:22:48.002 [error] <0.99.0> Supervisor control_sup had child tcp_acceptor started with tcp_acceptor:start() at undefined exit with reason {'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2017-05-18 16:22:48.003 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,tcp_acceptor,{'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2017-05-18 16:22:48.003 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,tcp_acceptor,{'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-18 16:52:14.439 [error] <0.99.0> Supervisor control_sup had child tcp_acceptor started with tcp_acceptor:start() at undefined exit with reason {'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2017-05-18 16:52:14.440 [error] <0.98.0> Supervisor chat_sup had child control_sup started with control_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,tcp_acceptor,{'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2017-05-18 16:52:14.440 [error] <0.96.0> CRASH REPORT Process <0.96.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,control_sup,{shutdown,{failed_to_start_child,tcp_acceptor,{'EXIT',{undef,[{tcp_acceptor,start,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}}}},{chat_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-05-18 16:57:30.561 [error] <0.149.0> gen_server tcp_acceptor terminated with reason: no match of right hand value {error,{invalid_child_spec,[]}} in tcp_acceptor:process_Client_Socket/1 line 182
2017-05-18 16:57:30.692 [error] <0.149.0> CRASH REPORT Process tcp_acceptor with 0 neighbours exited with reason: no match of right hand value {error,{invalid_child_spec,[]}} in tcp_acceptor:process_Client_Socket/1 line 182 in gen_server:terminate/7 line 812
2017-05-18 16:57:30.693 [error] <0.99.0> Supervisor control_sup had child tcp_acceptor started with tcp_acceptor:start_link() at <0.149.0> exit with reason no match of right hand value {error,{invalid_child_spec,[]}} in tcp_acceptor:process_Client_Socket/1 line 182 in context child_terminated
2017-05-18 17:13:49.789 [error] <0.152.0> gen_server tcp_acceptor terminated with reason: no match of right hand value {error,{invalid_child_spec,[]}} in tcp_acceptor:process_Client_Socket/1 line 182
2017-05-18 17:13:49.789 [error] <0.152.0> CRASH REPORT Process tcp_acceptor with 0 neighbours exited with reason: no match of right hand value {error,{invalid_child_spec,[]}} in tcp_acceptor:process_Client_Socket/1 line 182 in gen_server:terminate/7 line 812
2017-05-18 17:13:49.789 [error] <0.99.0> Supervisor control_sup had child tcp_acceptor started with tcp_acceptor:start_link() at <0.152.0> exit with reason no match of right hand value {error,{invalid_child_spec,[]}} in tcp_acceptor:process_Client_Socket/1 line 182 in context child_terminated
2017-05-18 17:34:33.255 [error] <0.149.0> gen_server tcp_acceptor terminated with reason: no match of right hand value {error,{{already_started,<0.149.0>},{child,undefined,#Port<0.3742>,{tcp_acceptor,start_link,[]},temporary,brutal_kill,worker,[tcp_acceptor]}}} in tcp_acceptor:process_Client_Socket/1 line 186
2017-05-18 17:34:33.360 [error] <0.149.0> CRASH REPORT Process tcp_acceptor with 0 neighbours exited with reason: no match of right hand value {error,{{already_started,<0.149.0>},{child,undefined,#Port<0.3742>,{tcp_acceptor,start_link,[]},temporary,brutal_kill,worker,[tcp_acceptor]}}} in tcp_acceptor:process_Client_Socket/1 line 186 in gen_server:terminate/7 line 812
2017-05-18 17:34:33.360 [error] <0.99.0> Supervisor control_sup had child tcp_acceptor started with tcp_acceptor:start_link() at <0.149.0> exit with reason no match of right hand value {error,{{already_started,<0.149.0>},{child,undefined,#Port<0.3742>,{tcp_acceptor,start_link,[]},temporary,brutal_kill,worker,[tcp_acceptor]}}} in tcp_acceptor:process_Client_Socket/1 line 186 in context child_terminated
2017-05-18 18:19:46.454 [error] <0.151.0> gen_fsm <0.151.0> in state wait_socket terminated with reason: "error tcp message"
2017-05-18 18:19:46.575 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: "error tcp message" in gen_fsm:terminate/7 line 559
2017-05-18 18:19:46.575 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason "error tcp message" in context child_terminated
2017-05-18 18:23:31.235 [error] <0.151.0> gen_fsm <0.151.0> in state wait_socket terminated with reason: "error tcp message"
2017-05-18 18:23:31.404 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: "error tcp message" in gen_fsm:terminate/7 line 559
2017-05-18 18:23:31.405 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason "error tcp message" in context child_terminated
2017-05-18 18:25:40.354 [error] <0.151.0> gen_fsm <0.151.0> in state wait_socket terminated with reason: "error tcp message"
2017-05-18 18:25:40.418 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: "error tcp message" in gen_fsm:terminate/7 line 559
2017-05-18 18:25:40.418 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason "error tcp message" in context child_terminated
2017-05-18 18:31:32.061 [error] <0.151.0> gen_fsm <0.151.0> in state wait_socket terminated with reason: "error tcp message"
2017-05-18 18:31:32.164 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: "error tcp message" in gen_fsm:terminate/7 line 559
2017-05-18 18:31:32.164 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason "error tcp message" in context child_terminated
2017-05-18 19:32:50.513 [error] <0.151.0> gen_fsm <0.151.0> in state wait_socket terminated with reason: "error tcp message"
2017-05-18 19:32:50.546 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: "error tcp message" in gen_fsm:terminate/7 line 559
2017-05-18 19:32:50.546 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason "error tcp message" in context child_terminated
2017-05-18 20:15:37.149 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: {error,{1,invalid_json}}
2017-05-18 20:15:37.237 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: {error,{1,invalid_json}} in gen_fsm:terminate/7 line 559
2017-05-18 20:15:37.237 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: {error,{1,invalid_json}} in context child_terminated
2017-05-18 20:18:37.990 [error] <0.152.0> gen_fsm <0.152.0> in state wait_auth terminated with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212
2017-05-18 20:18:38.109 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in gen_fsm:terminate/7 line 559
2017-05-18 20:18:38.109 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3753> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in context child_terminated
2017-05-18 20:18:43.999 [error] <0.154.0> gen_fsm <0.154.0> in state wait_auth terminated with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212
2017-05-18 20:18:43.999 [error] <0.154.0> CRASH REPORT Process <0.154.0> with 0 neighbours exited with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in gen_fsm:terminate/7 line 559
2017-05-18 20:18:44.000 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3766> started with {tcp_agent,start_link,undefined} at <0.154.0> exit with reason no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in context child_terminated
2017-05-18 20:18:47.013 [error] <0.155.0> gen_fsm <0.155.0> in state wait_socket terminated with reason: "error tcp message"
2017-05-18 20:18:47.013 [error] <0.155.0> CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: "error tcp message" in gen_fsm:terminate/7 line 559
2017-05-18 20:18:47.013 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3767> started with {tcp_agent,start_link,undefined} at <0.155.0> exit with reason "error tcp message" in context child_terminated
2017-05-18 20:21:11.991 [error] <0.151.0> gen_fsm <0.151.0> in state wait_socket terminated with reason: "error tcp message"
2017-05-18 20:21:12.025 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: "error tcp message" in gen_fsm:terminate/7 line 559
2017-05-18 20:21:12.025 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason "error tcp message" in context child_terminated
2017-05-18 20:21:44.441 [error] <0.152.0> gen_fsm <0.152.0> in state wait_auth terminated with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212
2017-05-18 20:21:44.441 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in gen_fsm:terminate/7 line 559
2017-05-18 20:21:44.441 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3761> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in context child_terminated
2017-05-18 20:22:58.294 [error] <0.154.0> gen_fsm <0.154.0> in state wait_auth terminated with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212
2017-05-18 20:22:58.294 [error] <0.154.0> CRASH REPORT Process <0.154.0> with 0 neighbours exited with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in gen_fsm:terminate/7 line 559
2017-05-18 20:22:58.294 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3766> started with {tcp_agent,start_link,undefined} at <0.154.0> exit with reason no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in context child_terminated
2017-05-18 20:23:28.877 [error] <0.155.0> gen_fsm <0.155.0> in state wait_auth terminated with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212
2017-05-18 20:23:28.877 [error] <0.155.0> CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in gen_fsm:terminate/7 line 559
2017-05-18 20:23:28.877 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3768> started with {tcp_agent,start_link,undefined} at <0.155.0> exit with reason no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in context child_terminated
2017-05-18 20:24:19.646 [error] <0.157.0> gen_fsm <0.157.0> in state wait_auth terminated with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212
2017-05-18 20:24:19.646 [error] <0.157.0> CRASH REPORT Process <0.157.0> with 0 neighbours exited with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in gen_fsm:terminate/7 line 559
2017-05-18 20:24:19.646 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3769> started with {tcp_agent,start_link,undefined} at <0.157.0> exit with reason no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in context child_terminated
2017-05-18 20:25:14.148 [error] <0.158.0> gen_fsm <0.158.0> in state wait_auth terminated with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212
2017-05-18 20:25:14.148 [error] <0.158.0> CRASH REPORT Process <0.158.0> with 0 neighbours exited with reason: no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in gen_fsm:terminate/7 line 559
2017-05-18 20:25:14.148 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3770> started with {tcp_agent,start_link,undefined} at <0.158.0> exit with reason no match of right hand value #{<<"cmd">> => 1,<<"password">> => <<"123">>,<<"username">> => <<"yangwei">>} in tcp_agent:handle_info/3 line 212 in context child_terminated
2017-05-18 20:26:50.653 [error] <0.151.0> gen_fsm <0.151.0> in state wait_socket terminated with reason: "error tcp message"
2017-05-18 20:26:50.668 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: "error tcp message" in gen_fsm:terminate/7 line 559
2017-05-18 20:26:50.668 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason "error tcp message" in context child_terminated
2017-05-18 20:27:00.491 [error] <0.152.0> gen_fsm <0.152.0> in state wait_socket terminated with reason: "error tcp message"
2017-05-18 20:27:00.491 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: "error tcp message" in gen_fsm:terminate/7 line 559
2017-05-18 20:27:00.491 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3761> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason "error tcp message" in context child_terminated
2017-05-18 20:27:06.070 [error] <0.153.0> gen_fsm <0.153.0> in state wait_socket terminated with reason: "error tcp message"
2017-05-18 20:27:06.070 [error] <0.153.0> CRASH REPORT Process <0.153.0> with 0 neighbours exited with reason: "error tcp message" in gen_fsm:terminate/7 line 559
2017-05-18 20:27:06.070 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3762> started with {tcp_agent,start_link,undefined} at <0.153.0> exit with reason "error tcp message" in context child_terminated
2017-05-18 20:27:34.107 [error] <0.154.0> gen_fsm <0.154.0> in state wait_socket terminated with reason: "error tcp message"
2017-05-18 20:27:34.107 [error] <0.154.0> CRASH REPORT Process <0.154.0> with 0 neighbours exited with reason: "error tcp message" in gen_fsm:terminate/7 line 559
2017-05-18 20:27:34.107 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3763> started with {tcp_agent,start_link,undefined} at <0.154.0> exit with reason "error tcp message" in context child_terminated
2017-05-18 20:28:29.308 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: "error cmd"
2017-05-18 20:28:29.316 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: "error cmd" in gen_fsm:terminate/7 line 559
2017-05-18 20:28:29.316 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason "error cmd" in context child_terminated
2017-05-18 20:32:21.674 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-18 20:32:21.801 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-18 20:32:21.801 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-18 20:36:28.602 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-18 20:36:28.675 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-18 20:36:28.675 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-18 20:37:34.414 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-18 20:37:34.415 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-18 20:37:34.415 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-18 20:38:24.952 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-18 20:38:24.953 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-18 20:38:24.953 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-18 20:39:23.662 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-18 20:39:23.664 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-18 20:39:23.664 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-18 20:41:57.913 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-18 20:41:57.930 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-18 20:41:57.930 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-18 20:44:02.818 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-18 20:44:02.833 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-18 20:44:02.834 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-18 20:45:18.197 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-18 20:45:18.215 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-18 20:45:18.215 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 11:17:54.606 [error] <0.156.0> gen_fsm <0.156.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 11:17:54.715 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 11:17:54.715 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.156.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 11:18:20.710 [error] <0.159.0> gen_fsm <0.159.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 11:18:20.710 [error] <0.159.0> CRASH REPORT Process <0.159.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 11:18:20.710 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3766> started with {tcp_agent,start_link,undefined} at <0.159.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 11:54:42.379 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: "error cmd"
2017-05-19 11:54:42.416 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: "error cmd" in gen_fsm:terminate/7 line 559
2017-05-19 11:54:42.417 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason "error cmd" in context child_terminated
2017-05-19 14:18:23.273 [error] <0.152.0> gen_fsm <0.152.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 14:18:23.311 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 14:18:23.311 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 14:19:57.651 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 14:19:57.680 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 14:19:57.680 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 14:21:31.744 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 14:21:31.761 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 14:21:31.761 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 14:23:03.300 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 14:23:03.330 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 14:23:03.330 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 14:23:53.437 [error] <0.151.0> gen_fsm <0.151.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 14:23:53.598 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 14:23:53.598 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.151.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 14:30:01.321 [error] <0.154.0> gen_fsm <0.154.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 14:30:01.443 [error] <0.154.0> CRASH REPORT Process <0.154.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 14:30:01.443 [error] <0.148.0> Supervisor tcp_agent_sup had child #Port<0.3761> started with {tcp_agent,start_link,undefined} at <0.154.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 14:42:11.799 [error] <0.155.0> gen_fsm <0.155.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 14:42:11.898 [error] <0.155.0> CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 14:42:11.898 [error] <0.152.0> Supervisor tcp_agent_sup had child #Port<0.3743> started with {tcp_agent,start_link,undefined} at <0.155.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 14:52:58.753 [error] <0.152.0> gen_fsm <0.152.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 14:52:58.863 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 14:52:58.864 [error] <0.149.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 14:54:13.766 [error] <0.152.0> gen_fsm <0.152.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 14:54:13.966 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 14:54:13.966 [error] <0.149.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 14:56:25.522 [error] <0.152.0> gen_fsm <0.152.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 14:56:25.637 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 14:56:25.637 [error] <0.149.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 14:59:04.053 [error] <0.152.0> gen_fsm <0.152.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 14:59:04.175 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 14:59:04.175 [error] <0.149.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 15:00:26.878 [error] <0.172.0> gen_fsm <0.172.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 15:00:26.891 [error] <0.172.0> CRASH REPORT Process <0.172.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 15:00:26.891 [error] <0.169.0> Supervisor tcp_agent_sup had child #Port<0.4430> started with {tcp_agent,start_link,undefined} at <0.172.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 15:09:05.071 [error] <0.152.0> gen_fsm <0.152.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 15:09:05.205 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 15:09:05.205 [error] <0.149.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 15:11:11.037 [error] <0.152.0> gen_fsm <0.152.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 15:11:11.119 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 15:11:11.119 [error] <0.149.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 15:15:54.395 [error] <0.152.0> gen_fsm <0.152.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 15:15:54.506 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 15:15:54.506 [error] <0.149.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason bad return value: ok in context child_terminated
2017-05-19 15:24:44.890 [error] <0.152.0> gen_fsm <0.152.0> in state wait_auth terminated with reason: bad return value: ok
2017-05-19 15:24:44.965 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad return value: ok in gen_fsm:terminate/7 line 559
2017-05-19 15:24:44.966 [error] <0.149.0> Supervisor tcp_agent_sup had child #Port<0.3742> started with {tcp_agent,start_link,undefined} at <0.152.0> exit with reason bad return value: ok in context child_terminated
